odin: bluetooth: Fix undefined PROPERTY_VALUE_MAX
 * vendor/qcom/opensource/commonsys/bluetooth_ext/system_bt_ext/bta/swb/bta_ag_swb.cc:142:14: error: use of undeclared identifier 'PROPERTY_VALUE_MAX'
   char value[PROPERTY_VALUE_MAX];

 * This reverts commit 0be25326c189ad809f0c3daa04f9961b4dbbd1c8.

Change-Id: Iaa9458296d71feacc88f5f04d7f5b99616115f23